### PR TITLE
Only display label "powered by PayPal" when FUNDING.CARD is allowed

### LINKED ISSUE #830: Unexpected margin at the bottom of SPB when style from 'medium' to 'responsive'
### Description

- I'm using the latest checkout.js
- Chrome: Version 68.0.3440.106 (Official Build) (64-bit)

When change the style from 'medium' to 'responsive', the text 'Powered by PayPal' is gone, but the extra margin still there in the bottom. Our partner does NOT expect that.

- when 'medium'
image

- when 'responsive'
image

### Steps to reproduce

Change the style to 'responsive'

_style: {
            ...
            size:   'responsive',   
            ...    
        },_

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

### PR DESCRIPTION
**Pull request by khanghoang**
This PR will fix #830 

In details: Check to see if `FUNDING.CARD` is disallowed before calculating the height for SPB and displaying the "powered by PayPal" label.

### CODE REVIEW

File: src/button/template/containerTemplate.jsx [hunk 1]
```diff
@@ -64,7 +64,10 @@ function getDimensions({ label, size, tagline, fundingicons, layout, number, vie
         height = (buttonHeight * number) + (perc(buttonHeight, BUTTON_RELATIVE_STYLE.VERTICAL_MARGIN) * (number - 1));
     }
 
-    if ((cards && cards.length > 0) && layout === BUTTON_LAYOUT.VERTICAL) {
+    const disallowedFundings = (funding && funding.disallowed) || [];
+    const isFundingCardDisallowed = disallowedFundings.indexOf(FUNDING.CARD) >= 0;
+
+    if (!isFundingCardDisallowed && (cards && cards.length > 0) && layout === BUTTON_LAYOUT.VERTICAL) {
```
Comment (bluepnume) [inline src/button/template/containerTemplate.jsx]: Can you check if `sources.indexOf(FUNDING.CARD) !== -1`

Comment (khanghoang) [reply src/button/template/containerTemplate.jsx]: I've thought about this but I assume that FUNDING.CARD is enabled by default for vertical integration, isn't it?

Comment (bluepnume) [reply src/button/template/containerTemplate.jsx]: Yeah it is -- but in that case it should still appear in `sources`. `sources` is the final list of eligible funding.

**Comment by khanghoang** [comment]
@bluepnume does the PR look good? I'd like to get it merged.
